
<!-- Blog Section-->
<section class="blog gray-bg">
    <div class="container">
        <header class="text-center">
            <h2 class="text-uppercase"><small>Made it hard way</small>Latest from the blog</h2>
        </header>
        <div class="row">
            <!-- post-->
            <div class="col-lg-6">
                <div class="post post-gray d-flex align-items-center flex-md-row flex-column">
                    <div class="thumbnail d-flex-align-items-center justify-content-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/blog-1.jpg" alt="..."></div>
                    <div class="info">
                        <h4 class="h5"> <a href="post.html">Newest photo apps          </a></h4><span class="date"><i class="fa fa-clock-o"></i>May 10th 2016</span>
                        <p>ellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Aenean ultricies mi vitae est. </p><a href="post.html" class="read-more">Read More<i class="fa fa-long-arrow-right"></i></a>
                    </div>
                </div>
            </div>
            <!-- /end post-->
            <!-- post-->
            <div class="col-lg-6">
                <div class="post post-gray d-flex align-items-center flex-md-row flex-column">
                    <div class="thumbnail d-flex-align-items-center justify-content-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/blog-2.jpg" alt="..."></div>
                    <div class="info">
                        <h4 class="h5"> <a href="post.html">Best books about Photography          </a></h4><span class="date"><i class="fa fa-clock-o"></i>May 10th 2016</span>
                        <p>Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.  Mauris placerat eleifend leo.</p><a href="post.html" class="read-more">Read More<i class="fa fa-long-arrow-right"></i></a>
                    </div>
                </div>
            </div>
            <!-- /end post-->
        </div>
    </div>
</section>