<!-- Hero Section-->
<section class="hero hero-home no-padding">
    <!-- Hero Slider-->
    <div class="owl-carousel owl-theme hero-slider">
        <div style="background: url(/img/communitas/the_path.jpg);" class="item d-flex align-items-center has-pattern">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 text-white">
                        <h1><?=$this->translate('On the way to the new world')?></h1>
                        <p class="lead"><?=$this->translate('It is time to leave yesterday\'s world behind and to shape the new world with love.')?></p>
                        <!--
                        <ul class="lead">
                            <li><strong>Educate yourselfs</strong> to be whatever we want</li>
                            <li><strong>Research & Share</strong> knowledge across borders</li>
                            <li><strong>Build a community</strong> to manifest love in daily life </li>
                            <li><strong>Transform the world</strong> be the change you want to see</li>
                        </ul> --><a href="#" class="btn btn-success wide shop-now"><?=$this->translate('Start now')?><i class="icon-play"> </i></a>
                    </div>
                </div>
            </div>
        </div>
        <div style="background: url(/img/communitas/together.jpg);" class="item d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 text-white">
                        <h1>Better together</h1>
                        <p class="lead">As Q showed as in such a beautiful way - the truth is within us. Together we are able to find truth, even when its covered in tons of lies.</p><a href="#" class="btn btn-success wide shop-now">Join us<i class="icon-bag">  </i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
