<div class="hero-icons">
    <!-- Service Block-->
    <div class="services-block">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 d-flex justify-content-center justify-content-lg-start">
                    <div class="item d-flex align-items-center">
                        <div class="icon"><i class="icon-truck"></i></div>
                        <div class="text">
                            <h6 class="no-margin text-uppercase"><?=$this->translate('Educate yourself')?></h6><span><?=$this->translate('to be whatever we want')?></span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-flex justify-content-center">
                    <div class="item d-flex align-items-center">
                        <div class="icon"><i class="icon-coin"></i></div>
                        <div class="text">
                            <h6 class="no-margin text-uppercase"><?=$this->translate('Research & Share')?></h6><span><?=$this->translate('knowledge across borders')?></span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-flex justify-content-center">
                    <div class="item d-flex align-items-center">
                        <div class="icon"><i class="icon-headphones"></i></div>
                        <div class="text">
                            <h6 class="no-margin text-uppercase"><?=$this->translate('Build a community')?></h6><span><?=$this->translate('be the change you want to see')?></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>