<form action="" method="POST" enctype="multipart/form-data" class="plc-core-basic-form">
    <?php if(isset($this->oItem)) { ?>
    <input type="hidden" name="Item_ID" value="<?=$this->oItem->getID()?>" />
    <?php } ?>
    <?php if(isset($this->iRefIDFS)) { ?>
        <input type="hidden" name="ref_idfs" value="<?=$this->iRefIDFS?>" />
    <?php } ?>
    <div class="row">
        <?= $this->partial('partial/basictabs', ['sFormName'=>$this->sFormName]); ?>
        <?php
        $aPartialData = ['sFormName'=>$this->sFormName,'oItem'=>$this->oItem];
        if(isset($this->aPartialExtraData)) {
            $aPartialData['aPartialExtraData'] = $this->aPartialExtraData;
        }
        ?>
        <?= $this->partial('partial/basictabcontents',$aPartialData); ?>
    </div>
</form>