<?php
/**
 * Print Form Field based on Type
 */
switch($oField->type) {
    case 'text': ?>
        <input type="text" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? $this->oItem->getTextField($oField->fieldkey) : ''?>" />
        <?php
        break;
    case 'password': ?>
        <input type="password" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? '*****************' : ''?>" />
        <?php
        break;
    case 'email': ?>
        <input type="email" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? $this->oItem->getTextField($oField->fieldkey) : ''?>" />
        <?php
        break;
    case 'tel': ?>
        <input type="tel" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" />
        <?php
        break;
    case 'date': ?>
        <input type="date" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" />
        <?php
        break;
    case 'time': ?>
        <input type="time" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" />
        <?php
        break;
    case 'partial':
        $aPartialData = [];
        $sPartialMode = (isset($this->oItem)) ? 'edit' : 'add';
        if(isset($this->layout()->aPartialData)) {
            if(array_key_exists($oField->fieldkey,$this->layout()->aPartialData)) {
                $aPartialData = $this->layout()->aPartialData[$oField->fieldkey];
            }
        }
        ?>
        <?= $this->partial('partial/'.$oField->fieldkey.'-'.$sPartialMode, ['sFormName'=>$this->sFormName,'oField'=>$oField,'oItem'=>$this->oItem,'aPartialData'=>$aPartialData]); ?>
        <?php
        break;
    default:
        break;
}