<?php
/**
 * Print Form Field based on Type
 */

use Application\Controller\CoreController;

$iItemID = (isset($this->oItem)) ? $this->oItem->getID() : 0;
$sExtraAttributes = '';
if($oField->readonly == 1) {
    $sExtraAttributes .= ' readonly';
}
switch($oField->type) {
    case 'gallery': ?>
        <?php if(isset($oItem)) { ?>
            <div id="drag-drop-area"></div>
            <script src="/vendor/uppy/dist/uppy.min.js"></script>
            <script>
                var uppy = Uppy.Core()
                    .use(Uppy.Dashboard, {
                        inline: true,
                        target: '#drag-drop-area'
                    })
                    .use(Uppy.XHRUpload, {
                        endpoint: '/uppy', headers: {
                            'entity_id': '<?=$oItem->getID()?>',
                            'entity_type': '<?=explode('-', $this->sFormName)[0]?>'
                        }
                    })

                uppy.on('file-added', (file) => {
                    uppy.setFileMeta(file.id, {
                        entity_id: '<?=$oItem->getID()?>',
                        entity_type: '<?=explode('-', $this->sFormName)[0]?>'
                    })
                })

                uppy.on('complete', (result) => {
                    console.log('Upload complete! We’ve uploaded these files:', result.successful)
                })

                <?php foreach(glob($_SERVER['DOCUMENT_ROOT'] . '/data/' . explode('-', $this->sFormName)[0] . '/' . $oItem->getID() . '/*{jpg,png}', GLOB_BRACE) as $sImg) {
                if (basename($sImg) == $oItem->getTextField('featured_image')) {
                    continue;
                }
                ?>
                console.log('<?=$sImg?>');
                fetch('/data/<?=explode('-', $this->sFormName)[0]?>/<?=$oItem->getID()?>/<?=basename($sImg)?>')
                    .then((response) => response.blob()) // returns a Blob
                    .then((blob) => {
                        uppy.addFile({
                            name: '<?=basename($sImg)?>', // image name
                            type: blob.type,
                            data: blob,
                            remote: false,
                            source: 'preload'
                        });
                    }).then(() => {
                    uppy.getFiles().forEach(file => {
                        if (file.source == "preload") {
                            // source = remote is how I "mark" them previoulsy
                            uppy.setFileState(file.id, {
                                progress: {uploadComplete: true, uploadStarted: true}
                            });
                        }
                    });
                });
                <?php
                } ?>
                $(function () {
                    $(document).on('click', '.plc-uppy-remove-image', function () {
                        alert('rm');
                        return false;
                    });
                    $('.uppy-DashboardItem-previewImg').on('click', function () {
                        var imgSrc = $(this).attr('src');
                        Swal.fire({
                            imageUrl: imgSrc,
                            imageHeight: 300,
                            width: 600,
                            imageAlt: 'A tall image'
                        });
                        return false;
                    });

                    $('.uppy-DashboardItem-progress').each(function () {
                        $(this).replaceWith('<i class="fas fa-trash plc-uppy-remove-image"></i>');
                    });
                });
            </script>
            <?php
        }
        break;
    /**
     * Text Field
     */
    case 'url':
    case 'text': ?>
        <input type="text" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? $this->oItem->getTextField($oField->fieldkey) : ''?>"<?=$sExtraAttributes?> />
        <?php
        break;
    /**
     * Textarea
     */
    case 'textarea': ?>
        <textarea class="form-control plcnote" rows="10" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"<?=$sExtraAttributes?> ><?=(isset($this->oItem)) ? $this->oItem->getTextField($oField->fieldkey) : ''?></textarea>
        <?php
        break;
    /**
     * Password field
     */
    case 'password': ?>
        <input type="password" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? '*****************' : ''?>"<?=$sExtraAttributes?> />
        <?php
        break;
    /**
     * E-Mail field
     */
    case 'email': ?>
        <input type="email" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? $this->oItem->getTextField($oField->fieldkey) : ''?>"<?=$sExtraAttributes?> />
        <?php
        break;
    /**
     * Tel (phone) field
     */
    case 'tel': ?>
        <input type="tel" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"<?=$sExtraAttributes?> />
        <?php
        break;
    /**
     * Date field
     */
    case 'date': ?>
        <input type="date" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? date('Y-m-d',strtotime($this->oItem->getTextField($oField->fieldkey))) : ''?>"<?=$sExtraAttributes?> />
        <?php
        break;
    /**
     * Datetime (Date + Time) field
     */
    case 'datetime': ?>
        <input type="date" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? date('Y-m-d',strtotime($this->oItem->getTextField($oField->fieldkey))) : ''?>"<?=$sExtraAttributes?> />
        <input type="time" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>-time"
               value="<?=(isset($this->oItem)) ? date('H:i',strtotime($this->oItem->getTextField($oField->fieldkey))) : ''?>"<?=$sExtraAttributes?> />
        <?php
        break;
    /**
     * Time field
     */
    case 'time': ?>
        <input type="time" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" />
        <?php
        break;
    /**
     * Select field
     */
    case 'select':?>
        <select class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" id="plc-select-<?=$this->sFormName?>_<?=$oField->fieldkey?>"<?=$sExtraAttributes?> >
            <?php if(isset($this->oItem)) { ?>
                <?php if($this->oItem->getSelectFieldID($oField->fieldkey) != 0) { ?>
                    <option value="<?= $this->oItem->getSelectFieldID($oField->fieldkey) ?>">
                        <?php $sLabel = $this->oItem->getSelectField($oField->fieldkey);
                        if(is_object($sLabel)) {
                            echo $this->oItem->getSelectField($oField->fieldkey)->getLabel();
                        } else {
                            echo $this->oItem->getSelectField($oField->fieldkey);
                        } ?>
                    </option>
                    <?php
                }
            }
            ?>
        </select>
        <script>
            $('#plc-select-<?=$this->sFormName?>_<?=$oField->fieldkey?>').select2({
                ajax: {
                    url: '<?=str_replace(['##ID##'],[$iItemID],$oField->url_list)?>',
                    dataType: 'json'
                },
                <?php
                if($oField->tbl_permission != '') {
                    $aPermissionInfo = explode('-', $oField->tbl_permission);
                    if(CoreController::$oSession->oUser->hasPermission($aPermissionInfo[0], $aPermissionInfo[1])) { ?>
                tags: true,
                    <?php }
                }?>
                // tags: true, - allow creation of new entries
                <?php if($oField->allow_clear == 1) { ?>
                allowClear: true,
                <?php }?>
                placeholder: '<?=$this->translate($oField->label)?>'
            });
        </script>
        <?php
        break;
    /**
     * Multiselect field
     */
    case 'multiselect':?>
        <select class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>[]" id="plc-select-<?=$this->sFormName?>_<?=$oField->fieldkey?>" multiple>
            <?php if(isset($this->oItem)) { ?>
                <?php if(count($this->oItem->getMultiSelectFieldIDs($oField->fieldkey)) != 0) {
                    foreach($this->oItem->getMultiSelectField($oField->fieldkey) as $oItem) { ?>
                        <option value="<?= $oItem->id ?>">
                            <?= $oItem->text ?>
                        </option>
                        <?php
                    }
                }
            }
            ?>
        </select>
        <script>
            $('#plc-select-<?=$this->sFormName?>_<?=$oField->fieldkey?>').select2({
                ajax: {
                    url: '<?=str_replace(['##ID##'],[$iItemID],$oField->url_list)?>',
                    dataType: 'json'
                },
                <?php
                if($oField->tbl_permission != '') {
                $aPermissionInfo = explode('-', $oField->tbl_permission);
                if(CoreController::$oSession->oUser->hasPermission($aPermissionInfo[0], $aPermissionInfo[1])) { ?>
                tags: true,
                <?php }
                }?>
                // tags: true, - allow creation of new entries
                <?php if($oField->allow_clear == 1) { ?>
                allowClear: true,
                <?php }?>
                placeholder: '<?=$this->translate($oField->label)?>'
            });
            <?php
            # Add selected items to multiselect
            if(isset($this->oItem)) {
                if(count($this->oItem->getMultiSelectFieldIDs($oField->fieldkey)) != 0) {
                    foreach($this->oItem->getMultiSelectField($oField->fieldkey) as $oItem) { ?>
                    var option = new Option('<?=$oItem->text?>', <?=$oItem->id?>, true, true);
                    $('#plc-select-<?=$this->sFormName?>_<?=$oField->fieldkey?>').append(option).trigger('change');
                    <?php
                    }
                }
            } ?>
        </script>
        <?php
        break;
    /**
     * Currency Field
     */
    case 'currency': ?>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text">€</span>
            </div>
            <input type="text" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
                   value="<?=(isset($this->oItem)) ? number_format($this->oItem->getTextField($oField->fieldkey),2) : ''?>"<?=$sExtraAttributes?> />
        </div>
        <?php
        break;
    /**
     * Partial Field
     */
    case 'partial':
        $aPartialData = [];
        $sPartialMode = (isset($this->oItem)) ? 'edit' : 'add';
        if(isset($this->layout()->aPartialData)) {
            if(array_key_exists($oField->fieldkey,$this->layout()->aPartialData)) {
                $aPartialData = $this->layout()->aPartialData[$oField->fieldkey];
            }
        }
        if(isset($this->aPartialExtraData)) {
            $aPartialData = array_merge($aPartialData,$this->aPartialExtraData);
        }
        ?>
        <?= $this->partial('partial/'.$oField->fieldkey.'-'.$sPartialMode, ['sFormName'=>$this->sFormName,'oField'=>$oField,'oItem'=>$this->oItem,'aPartialData'=>$aPartialData]); ?>
        <?php
        break;
    default:
        break;
}