<div class="col-md-12">
    <ul class="nav nav-tabs" id="<?=$this->sFormName?>Form" role="tablist">
    <?php
    if(count($this->layout()->aTabs) > 0) {
        $iTabCount = 1;
        foreach($this->layout()->aTabs as $oTab) { ?>
            <li class="nav-item">
                <a class="nav-link<?=($iTabCount == 1) ? ' active' : ''?>" id="<?=$oTab->Tab_ID?>-tab" data-toggle="tab" href="#<?=$oTab->Tab_ID?>" role="tab" aria-controls="<?=$oTab->Tab_ID?>" aria-selected="<?=($iTabCount == 1) ? 'true' : 'false'?>">
                    <i class="<?=$oTab->icon?>"></i> <?=$this->translate($oTab->title)?><br /><small><?=$this->translate($oTab->subtitle)?></small>
                </a>
            </li>
        <?php
            $iTabCount++;
        }
    }
    ?>
    </ul>
    <div style="position:absolute; right:4px; top:0;">
        <a href="/form/updatefieldsort/<?=$this->sFormName?>" class="btn btn-default plc-change-form-field-sort" title="<?=$this->translate('Change Field Order')?>"><i class="fas fa-sort-numeric-up"></i></a>
    </div>
</div>
