<?php
/**
 * Print Form Field based on Type
 */
$iItemID = (isset($this->oItem)) ? $this->oItem->getID() : 0;
switch($oField->type) {
    case 'text': ?>
        <input type="text" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? $this->oItem->getTextField($oField->fieldkey) : ''?>" />
        <?php
        break;
    case 'textarea': ?>
        <textarea class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"><?=(isset($this->oItem)) ? $this->oItem->getTextField($oField->fieldkey) : ''?></textarea>
        <?php
        break;
    case 'password': ?>
        <input type="password" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? '*****************' : ''?>" />
        <?php
        break;
    case 'email': ?>
        <input type="email" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? $this->oItem->getTextField($oField->fieldkey) : ''?>" />
        <?php
        break;
    case 'tel': ?>
        <input type="tel" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" />
        <?php
        break;
    case 'date': ?>
        <input type="date" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? date('Y-m-d',strtotime($this->oItem->getTextField($oField->fieldkey))) : ''?>" />
        <?php
        break;
    case 'datetime': ?>
        <input type="date" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>"
               value="<?=(isset($this->oItem)) ? date('Y-m-d',strtotime($this->oItem->getTextField($oField->fieldkey))) : ''?>" />
        <input type="time" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>-time"
               value="<?=(isset($this->oItem)) ? date('H:i',strtotime($this->oItem->getTextField($oField->fieldkey))) : ''?>" />
        <?php
        break;
    case 'time': ?>
        <input type="time" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" />
        <?php
        break;
    case 'select':?>
        <select class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" id="plc-select-<?=$this->sFormName?>_<?=$oField->fieldkey?>">
            <?php if(isset($this->oItem)) { ?>
            <option value="<?=$this->oItem->getSelectFieldID($oField->fieldkey)?>">
                <?=$this->oItem->getSelectField($oField->fieldkey)->getLabel()?>
            </option>
            <?php } ?>
        </select>
        <script>
            $('#plc-select-<?=$this->sFormName?>_<?=$oField->fieldkey?>').select2({
                ajax: {
                    url: '<?=str_replace(['##ID##'],[$iItemID],$oField->url_ist)?>',
                    dataType: 'json'
                },
                // tags: true, - allow creation of new entries
                <?php if($oField->allow_clear == 1) { ?>
                allowClear: true,
                <?php }?>
                placeholder: '<?=$oField->label?>'
            });
        </script>
        <?php
        break;
    case 'partial':
        $aPartialData = [];
        $sPartialMode = (isset($this->oItem)) ? 'edit' : 'add';
        if(isset($this->layout()->aPartialData)) {
            if(array_key_exists($oField->fieldkey,$this->layout()->aPartialData)) {
                $aPartialData = $this->layout()->aPartialData[$oField->fieldkey];
            }
        }
        ?>
        <?= $this->partial('partial/'.$oField->fieldkey.'-'.$sPartialMode, ['sFormName'=>$this->sFormName,'oField'=>$oField,'oItem'=>$this->oItem,'aPartialData'=>$aPartialData]); ?>
        <?php
        break;
    default:
        break;
}