<td>
    <?php
    /**
     * Get Column Data based on type
     */
    switch($this->oCol->type) {
        case 'select':
            if($this->oItem->getSelectFieldID($this->oCol->fieldkey) != 0) {
                echo $this->oItem->getSelectField($this->oCol->fieldkey)->getLabel();
            }
            break;
        case 'text':
        case 'email':
            if($this->oCol->url_view != '') {
                $sFinalURL = str_replace(['##ID##'],[$this->oItem->getID()],$this->oCol->url_view);
                echo '<a href="'.$sFinalURL.'">';
                echo $this->oItem->getTextField($this->oCol->fieldkey);
                echo '</a>';
            } else {
                echo $this->oItem->getTextField($this->oCol->fieldkey);
            }
            break;
        case 'textarea':
            echo substr($this->oItem->getTextField($this->oCol->fieldkey),0,50);
            break;
        case 'date':
            $sDate = $this->oItem->getTextField($this->oCol->fieldkey);
            if($sDate != '0000-00-00 00:00:00' && !empty($sDate)) {
                echo date('d.m.Y',strtotime($sDate));
            } else {
                echo '-';
            }
            break;
        case 'datetime':
            $sDate = $this->oItem->getTextField($this->oCol->fieldkey);
            if($sDate != '0000-00-00 00:00:00' && !empty($sDate)) {
                echo date('d.m.Y H:i',strtotime($sDate));
            } else {
                echo '-';
            }
            break;
        default:
            break;
    }
    ?>
</td>