<td>
    <?php
    /**
     * Get Column Data based on type
     */
    switch($this->oCol->type) {
        case 'multiselect':
            if(count($this->oItem->getMultiSelectFieldIDs($this->oCol->fieldkey)) > 0) {
                $aData = $this->oItem->getMultiSelectField($this->oCol->fieldkey,true);
                foreach($aData as $oRow) {
                    echo $this->translate($oRow->getLabel());
                }
            }
            break;
        case 'select':
            if($this->oItem->getSelectFieldID($this->oCol->fieldkey) != 0) {
                $sLabel = $this->oItem->getSelectField($this->oCol->fieldkey);
                if(is_object($sLabel)) {
                    $sLabel = $sLabel->getLabel();
                }
                echo $this->translate($sLabel);
            }
            break;
        case 'text':
        case 'email':
            if($this->oCol->url_view != '') {
                $sFinalURL = str_replace(['##ID##'],[$this->oItem->getID()],$this->oCol->url_view);
                echo '<a href="'.$sFinalURL.'">';
                echo $this->oItem->getTextField($this->oCol->fieldkey);
                echo '</a>';
            } else {
                echo $this->oItem->getTextField($this->oCol->fieldkey);
            }
            break;
        case 'textarea':
            echo substr($this->oItem->getTextField($this->oCol->fieldkey),0,50);
            break;
        case 'date':
            $sDate = $this->oItem->getTextField($this->oCol->fieldkey);
            if($sDate != '0000-00-00 00:00:00' && !empty($sDate)) {
                if($this->oCol->url_view != '') {
                    $sFinalURL = str_replace(['##ID##'],[$this->oItem->getID()],$this->oCol->url_view);
                    echo '<a href="'.$sFinalURL.'">';
                        echo date('d.m.Y',strtotime($sDate));
                    echo '</a>';
                } else {
                    echo date('d.m.Y',strtotime($sDate));
                }
            } else {
                echo '-';
            }
            break;
        case 'datetime':
            $sDate = $this->oItem->getTextField($this->oCol->fieldkey);
            if($sDate != '0000-00-00 00:00:00' && !empty($sDate)) {
                if($sDate != '0000-00-00 00:00:00' && !empty($sDate)) {
                    if($this->oCol->url_view != '') {
                        $sFinalURL = str_replace(['##ID##'],[$this->oItem->getID()],$this->oCol->url_view);
                        echo '<a href="'.$sFinalURL.'">';
                            echo date('d.m.Y H:i',strtotime($sDate));
                        echo '</a>';
                    } else {
                        echo date('d.m.Y H:i',strtotime($sDate));
                    }
                } else {
                    echo '-';
                }
            } else {
                echo '-';
            }
            break;
        case 'currency':
            echo '€ '.number_format($this->oItem->getTextField($this->oCol->fieldkey),2,',','.');
            break;
        case 'featuredimage':
            if($this->oItem->hasFeaturedImage()) {
                if($this->oItem->featured_image != '') {
                    $sPath = explode('-',$sTableName)[0];
                    echo '<div class="rounded-circle" style="height:128px; width:128px; background:url(\'/data/'.$sPath.'/'.$this->oItem->getID().'/'.$this->oItem->featured_image.'\'); background-size: cover;"></div>';
                }
            }
            break;
        default:
            break;
    }
    ?>
</td>