<?php

use Application\Controller\CoreController;

# Load User Index Permissions as base for navigation
$aIndexPermissions = [];
if(is_object(CoreController::$oSession->oUser)) {
    $aIndexPermissions = CoreController::$oSession->oUser->getMyPermissions('index', true);
}
?>
<?php foreach(array_keys($aIndexPermissions) as $sModule) {
    $aInfo = $aIndexPermissions[$sModule];
    # Home is empty because there is no home permission
    if(count($aInfo) == 0) {
        $aInfo = ['index'=>(object)['nav_label'=>'Home','nav_href'=>'/']];
    }
    if($aInfo['index']->show_in_menu != 1) {
        continue;
    }
    # check if we are on active node
    $sActive = ('/'.strtolower($this->sRouteName) == strtolower($aInfo['index']->nav_href)) ? ' active' : '';
    # home is special case ..
    $sActive = ($this->sRouteName == 'home' && $aInfo['index']->nav_href == '/') ? ' active' : $sActive;
    ?>
    <li class="nav-item<?=$sActive?>">
        <a class="nav-link" href="<?=$aInfo['index']->nav_href?>">
            <?=$aInfo['index']->nav_label?>
        </a>
    </li>
<?php } ?>