<?php if ($this->pageCount): ?>
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->route, [], ['query' => ['page' => $this->previous]]) ?>">
                        &lt;&lt;
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        &lt;&lt;
                    </a>
                </li>
            <?php endif ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page !== $this->current): ?>
                    <li class="page-item">
                        <a class="page-link" href="<?= $this->url($this->route, [], ['query' => ['page' => $page]]) ?>">
                            <?= $page ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="page-item active">
                        <a class="page-link" href="#"><?= $page ?></a>
                    </li>
                <?php endif ?>
            <?php endforeach ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->route, [], ['query' => ['page' => $this->next]]) ?>">
                        &gt;&gt;
                    </a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <a class="page-link" href="#">
                        &gt;&gt;
                    </a>
                </li>
            <?php endif ?>
        </ul>
    </nav>
<?php endif ?>