<?php
/**
 * Print Form Field based on Type
 */
switch($oField->type) {
    case 'password':
        echo '*********************';
        break;
    case 'text':
    case 'textarea':
    case 'tel':
    case 'email':
        echo $this->oItem->getTextField($oField->fieldkey);
        break;
    case 'date':
        if($this->oItem->getTextField($oField->fieldkey) != '0000-00-00 00:00:00' && $this->oItem->getTextField($oField->fieldkey) != '0000-00-00') {
            echo date('d.m.Y',strtotime($this->oItem->getTextField($oField->fieldkey)));
        } else {
            echo '-';
        }
        break;
    case 'datetime':
        if($this->oItem->getTextField($oField->fieldkey) != '0000-00-00 00:00:00') {
            echo date('d.m.Y H:i',strtotime($this->oItem->getTextField($oField->fieldkey)));
        } else {
            echo '-';
        }
        break;
    case 'time': ?>
        <input type="time" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" />
        <?php
        break;
    case 'select':
        if($this->oItem->getSelectFieldID($oField->fieldkey) != 0) {
            echo $this->translate($this->oItem->getSelectField($oField->fieldkey)->getLabel());
        } else {
            echo '-';
        }
        break;
    case 'multiselect':
        if(count($this->oItem->getMultiSelectFieldIDs($oField->fieldkey)) != 0) {
            foreach($this->oItem->getMultiSelectField($oField->fieldkey) as $oItem) {
                echo $this->translate($oItem->text).', ';
            }
        } else {
            echo '-';
        }
        break;
    case 'gallery': ?>
        <div id="drag-drop-area"></div>
        <script src="https://transloadit.edgly.net/releases/uppy/v1.8.0/uppy.min.js"></script>
        <script>
            var uppy = Uppy.Core()
                .use(Uppy.Dashboard, {
                    inline: true,
                    target: '#drag-drop-area'
                })
                .use(Uppy.XHRUpload, {endpoint: '/uppy',headers: {
                        'entity_id': '<?=$oItem->getID()?>',
                        'entity_type': '<?=explode('-',$this->sFormName)[0]?>'
                    }})

            uppy.on('file-added', (file) => {
                uppy.setFileMeta(file.id, {
                    entity_id: '<?=$oItem->getID()?>',
                    entity_type: '<?=explode('-',$this->sFormName)[0]?>'
                })
            })

            uppy.on('complete', (result) => {
                console.log('Upload complete! We’ve uploaded these files:', result.successful)
            })

            <?php foreach(glob($_SERVER['DOCUMENT_ROOT'].'/data/'.explode('-',$this->sFormName)[0].'/'.$oItem->getID().'/*{jpg,png}',GLOB_BRACE) as $sImg) {
            if(basename($sImg) == $oItem->getTextField('featured_image')) {
                continue;
            }
            ?>
            console.log('<?=$sImg?>');
            fetch('/data/<?=explode('-',$this->sFormName)[0]?>/<?=$oItem->getID()?>/<?=basename($sImg)?>')
                .then((response) => response.blob()) // returns a Blob
                .then((blob) => {
                    uppy.addFile({
                        name: '<?=basename($sImg)?>', // image name
                        type: blob.type,
                        data: blob,
                        remote: false,
                        source:'preload'
                    });
                }).then(() => {
                uppy.getFiles().forEach(file => {
                    if(file.source == "preload") {
                        // source = remote is how I "mark" them previoulsy
                        uppy.setFileState(file.id, {
                            progress: { uploadComplete: true, uploadStarted: true }
                        });
                    }
                });
            });
            <?php
            } ?>
            $(function() {
                $(document).on('click','.plc-uppy-remove-image',function() {
                    alert('rm');
                    return false;
                });
                $('.uppy-DashboardItem-previewImg').on('click',function() {
                    var imgSrc = $(this).attr('src');
                    Swal.fire({
                        imageUrl: imgSrc,
                        imageHeight: 300,
                        width:600,
                        imageAlt: 'A tall image'
                    });
                    return false;
                });

                $('.uppy-DashboardItem-progress').each(function() {
                    $(this).replaceWith('<i class="fas fa-trash plc-uppy-remove-image"></i>');
                });
            });
        </script>
        <?php
        break;
    /**
     * Currency Field - View
     */
    case 'currency': ?>
        <div class="input-group mb-3">
            € <?=number_format($this->oItem->getTextField($oField->fieldkey),2,',','.')?>
        </div>
        <?php
        break;
    /**
     * Partial Field - View
     */
    case 'partial':
        $aPartialData = [];
        $sPartialMode = 'view';
        if(isset($this->layout()->aPartialData)) {
            if(array_key_exists($oField->fieldkey,$this->layout()->aPartialData)) {
                $aPartialData = $this->layout()->aPartialData[$oField->fieldkey];
            }
        }
        ?>
        <?= $this->partial('partial/'.$oField->fieldkey.'-'.$sPartialMode, ['sFormName'=>$this->sFormName,'oField'=>$oField,'oItem'=>$this->oItem,'aPartialData'=>$aPartialData]); ?>
        <?php
        break;
    default:
        break;
}