<?php
/**
 * Print Container and Label for each Field in Form
 */
if(array_key_exists($this->sTab,$this->aFormFieldsByTab)) {
    foreach($this->aFormFieldsByTab[$this->sTab] as $oField) {
        # skip hidden fields entirely
        if($oField->type == 'hidden') {
            continue;
        } ?>
        <!-- Field <?=$oField->fieldkey?> START -->
        <div class="form-group <?=$oField->class?>">
            <?php if($oField->type != 'partial' && $oField->type != 'gallery' && $oField->type != 'featuredimage') { ?>
            <label class="plcViewFormLabel" for="<?=$this->sFormName?>_<?=$oField->fieldkey?>">
                <?=$this->translate($oField->label)?>
            </label><br/>
            <?php } ?>
            <?php
            $aPartialData =['sFormName'=>$this->sFormName,'oField'=>$oField,'oItem'=>$this->oItem] ;
            if(isset($this->aPartialExtraData)) {
                $aPartialData['aPartialExtraData'] = $this->aPartialExtraData;
            }
            ?>
            <?= $this->partial('partial/viewformfield', $aPartialData); ?>
        </div>
        <!-- Field <?=$oField->fieldkey?> END -->
    <?php
    }
}
?>
