<?php
/**
 * Print Container and Label for each Field in Form
 */

$bHideLabels = (isset($this->bHideLabels)) ? $this->bHideLabels : false;
$bOnlyLabels = (isset($this->bOnlyLabels)) ? $this->bOnlyLabels : false;
if(array_key_exists($this->sTab,$this->aFormFieldsByTab)) {
    foreach($this->aFormFieldsByTab[$this->sTab] as $oField) {
        $iMargin = 0;

        # skip hidden fields entirely
        if($oField->type == 'hidden') {
            continue;
        }
        if($oField->type == 'boolselect') {
            $iMargin = '21px';
        }?>
        <!-- Field <?=$oField->fieldkey?> START -->
        <div class="form-group <?=$oField->class?>">
            <?php if($oField->type != 'partial' && $oField->type != 'gallery' && $oField->type != 'featuredimage' && !$bHideLabels && $oField->type != 'boolselect') { ?>
            <label class="plcViewFormLabel" for="<?=$this->sFormName?>_<?=$oField->fieldkey?>" style="top:6px; height:25px; overflow:hidden;">
                <?=$this->translate($oField->label)?>
            </label><br/>
            <?php } ?>
            <?php
            if(!$bOnlyLabels) {
                $aPartialData =['sFormName'=>$this->sFormName,'oField'=>$oField,'oItem'=>$this->oItem] ;
                if(isset($this->aPartialExtraData)) {
                    $aPartialData['aPartialExtraData'] = $this->aPartialExtraData;
                }
                ?>
                <div class="form-control" style="display: inline-block;  margin-top:<?=$iMargin?>; height:auto !important; padding-left:6px; min-height:34px; ">
                <?= $this->partial('partial/viewformfield', $aPartialData); ?>
                </div>
            <?php } ?>
        </div>
        <!-- Field <?=$oField->fieldkey?> END -->
    <?php
    }
}
?>
