<div class="plc-view-field-value">
    <?php
/**
 * Print Form Field based on Type
 */
switch($oField->type) {
    case 'password':
        echo '*********************';
        break;
    case 'text':
    case 'textarea':
    case 'tel':
    case 'email':
        echo $this->oItem->getTextField($oField->fieldkey);
        break;
    case 'url':
        echo '<a href="'.$this->oItem->getTextField($oField->fieldkey).'" target="_blank">';
            echo $this->oItem->getTextField($oField->fieldkey);
        echo '</a>';
        break;
    case 'date':
        if($this->oItem->getTextField($oField->fieldkey) != '0000-00-00 00:00:00' && $this->oItem->getTextField($oField->fieldkey) != '0000-00-00') {
            echo date('d.m.Y',strtotime($this->oItem->getTextField($oField->fieldkey)));
        } else {
            echo '-';
        }
        break;
    case 'datetime':
        if($this->oItem->getTextField($oField->fieldkey) != '0000-00-00 00:00:00') {
            echo date('d.m.Y H:i',strtotime($this->oItem->getTextField($oField->fieldkey)));
        } else {
            echo '-';
        }
        break;
    case 'time': ?>
        <input type="time" class="form-control" name="<?=$this->sFormName?>_<?=$oField->fieldkey?>" />
        <?php
        break;
    case 'select':
        if($this->oItem->getSelectFieldID($oField->fieldkey) != 0) {
            $sLabel = '-';
            if(is_object($this->oItem->getSelectField($oField->fieldkey))) {
                $sLabel = $this->oItem->getSelectField($oField->fieldkey)->getLabel();
            } else {
                $sLabel = $this->oItem->getSelectField($oField->fieldkey);
            }
            echo $this->translate($sLabel);
        } else {
            echo '-';
        }
        break;
    case 'multiselect':
        if(count($this->oItem->getMultiSelectFieldIDs($oField->fieldkey)) != 0) {
            foreach($this->oItem->getMultiSelectField($oField->fieldkey) as $oItem) {
                echo $this->translate($oItem->text).', ';
            }
        } else {
            echo '-';
        }
        break;
    case 'gallery':
        ?>
        <div style="width:100%; display:inline-block;">
        <?php foreach(glob($_SERVER['DOCUMENT_ROOT'].'/data/'.explode('-',$this->sFormName)[0].'/'.$this->oItem->getID().'/*{jpg,png}',GLOB_BRACE) as $sImg) {
            if (basename($sImg) == $this->oItem->getTextField('featured_image')) {
                continue;
            } ?>
            <div style="height:120px; width:120px; margin-right:12px; margin-bottom:12px; float:left; display:inline-block;">
                <div style="width:100%; height: 100%;">
                    <img src="/data/<?=explode('-',$this->sFormName)[0]?>/<?=$this->oItem->getID()?>/<?=basename($sImg)?>" style="width:100%; height: 100%;" />
                </div>
            </div><?php
        } ?>
        </div>
        <?php
        break;
    case 'upload':
        $sFile = $this->oItem->getTextField($oField->fieldkey);
        if($sFile != '') {
            $sExt = pathinfo($sFile)['extension'];
            switch($sExt) {
                case 'jpg':
                case 'jpeg':
                case 'gif':
                case 'png':
                case 'svg':
                    echo '<img src="/data/'.str_replace(['##ID##'],[$this->oItem->getID()],$oField->url_list).'/'.$sFile.'" style="max-width:600px; max-height:200px;" />';
                    echo $sFile;
                    break;
                default:
                    echo $sFile;
                    break;
            }
        } else {
            echo '-';
        }
        break;
    /**
     * Currency Field - View
     */
    case 'number':
        $fNumber = (float)$this->oItem->getTextField($oField->fieldkey);
        if($fNumber != 0) {
            $fNumber = number_format($fNumber,2,',','.');
        }
        ?>
        <div class="input-group mb-3">
            <?=$fNumber?>
        </div>
        <?php
        break;
    /**
     * Currency Field - View
     */
    case 'currency': ?>
        <div class="input-group mb-3">
            € <?=number_format($this->oItem->getTextField($oField->fieldkey),2,',','.')?>
        </div>
        <?php
        break;
    /**
     * Partial Field - View
     */
    case 'partial':
        $aPartialData = [];
        $sPartialMode = 'view';
        if(isset($this->layout()->aPartialData)) {
            if(array_key_exists($oField->fieldkey,$this->layout()->aPartialData)) {
                $aPartialData = $this->layout()->aPartialData[$oField->fieldkey];
            }
        }
        if(isset($this->aPartialExtraData)) {
            $aPartialData = array_merge($aPartialData,$this->aPartialExtraData);
        }
        ?>
        <?= $this->partial('partial/'.$oField->fieldkey.'-'.$sPartialMode, ['sFormName'=>$this->sFormName,'oField'=>$oField,'oItem'=>$this->oItem,'aPartialData'=>$aPartialData]); ?>
        <?php
        break;
    default:
        break;
}?>
</div>