<div class="plc-core-basic-view">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body text-center">
                    <?php if($oItem->hasFeaturedImage()) { ?>
                    <div style="max-width:250px; margin:auto;">
                        <!-- our filepond input -->
                        <input type="file" name="filepond" id="filepond">
                    </div>
                    <?php } ?>
                    <h2><?=$oItem->getLabel()?></h2>
                    <hr/>
                    <?php
                    $sCreatedDate = $oItem->getTextField('created_date');
                    if($sCreatedDate != '0000-00-00 00:00:00' && !empty($sCreatedDate)) { ?>
                    <div style="text-align: left;">
                        <small><?=$this->translate('Created')?>: <?=date('d.m.Y H:i',strtotime($sCreatedDate))?></small><br/>
                        <small><?=$this->translate('Last Edited')?>: <?=date('d.m.Y H:i',strtotime($oItem->getTextField('modified_date')))?></small>
                    </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card px-0">
                <div class="card-body px-0 py-2">
                    <?= $this->partial('partial/basictabs', ['sFormName'=>$this->sFormName]); ?>
                    <?= $this->partial('partial/basictabview', ['sFormName'=>$this->sFormName,'oItem'=>$this->oItem]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php if($oItem->hasFeaturedImage()) { ?>
<script>
    const fieldsetElement = document.getElementById('filepond');

    FilePond.registerPlugin(
        FilePondPluginFileValidateType,
        FilePondPluginImageExifOrientation,
        FilePondPluginImagePreview,
        FilePondPluginImageCrop,
        FilePondPluginImageResize,
        FilePondPluginImageTransform
    );
    FilePond.create(
        fieldsetElement,
        {
            labelIdle: `Drag & Drop your picture or <span class="filepond--label-action">Browse</span>`,
            imagePreviewHeight: 170,
            imageCropAspectRatio: '1:1',
            imageResizeTargetWidth: 200,
            imageResizeTargetHeight: 200,
            stylePanelLayout: 'compact circle',
            styleLoadIndicatorPosition: 'center bottom',
            styleProgressIndicatorPosition: 'right bottom',
            styleButtonRemoveItemPosition: 'left bottom',
            styleButtonProcessItemPosition: 'right bottom',
        }
    );

    FilePond.setOptions({
        server: {
            process: {
                url: '/filepond',
                method: 'POST',
                withCredentials: false,
                headers: {},
                timeout: 7000,
                onload: (response) => {
                    console.log(response);
                },
                onerror: (e) => {
                    $('#plc-featured-image').printMessage('Fehler',e.detail.error.main,'error');
                },
                ondata: (formData) => {
                    formData.append('type', '<?=explode('-',$this->sFormName)[0]?>');
                    formData.append('entity_id', '<?=$oItem->getID()?>');
                    return formData;
                }
            },
            load: '/'
        },
        <?php if($oItem->getTextField('featured_image')) { ?>
        files: [
            {
                // the server file reference
                source: '/data/<?=explode('-',$this->sFormName)[0]?>/<?=$oItem->getID()?>/<?=$oItem->getTextField('featured_image')?>',

                // set type to limbo to tell FilePond this is a temp file
                options: {
                    type: 'local'
                }
            }
        ]
        <?php } ?>
    });

    fieldsetElement.addEventListener('FilePond:error', e => {
        $('#plc-featured-image').printMessage('Fehler',e.detail.error.main,'error');
    });
    </script>
<?php } ?>