<?php

#echo $this->partial('becho/hero_slider', []);

echo $this->partial('becho/blog_slider2', []);

echo $this->partial('becho/eco_calendar', []);

echo $this->partial('becho/rss_feed', []);
/**
echo $this->partial('communitas/hero_icons', []);

echo $this->partial('communitas/project_slider', []);

echo $this->partial('communitas/verein_stats', []);

echo $this->partial('communitas/blog_slider', []);
 * **/