<?php
# Get Partial Data
$aFieldsByForm = $this->aPartialData['aFields'];
$aUserFields = $this->aPartialData['aUserFields'];


# Print List with all Modules and Fields
foreach(array_keys($aFieldsByForm) as $sForm) {
    $oForm = $aFieldsByForm[$sForm]['oForm'];
    $aFields = $aFieldsByForm[$sForm]['aFields']; ?>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><?=$oForm->label?></h3>
            </div>

            <div class="card-body">
                <ul class="list-group" style="display: inline-block; width:100%;">
                    <?php foreach($aFields as $oField) {
                        //var_dump($oField);
                        $bHasPerm = false;

                        if(array_key_exists($oForm->form_key,$aUserFields)) {
                            if(array_key_exists($oField->Field_ID,$aUserFields[$oForm->form_key])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <li class="list-group-item col-md-6" style="position: relative; float:left;">
                            <input type="checkbox"<?=($bHasPerm) ? ' checked' : ''?> name="<?=$this->sFormName?>-formfields[]" value="<?=$oField->Field_ID?>_<?=$oForm->form_key?>" />
                            <?=$oField->label?>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>
    <?php
}

