<?php
# Get Partial Data
$aColumnsByTable = $this->aPartialData['aColumns'];
$aUserColumns = $this->aPartialData['aUserColumns'];

//var_dump($aUserColumns);

# Print List with all Modules and Columns
foreach(array_keys($aColumnsByTable) as $sTable) {
    $oTbl = $aColumnsByTable[$sTable]['oTable'];
    $aFields = $aColumnsByTable[$sTable]['aFields']; ?>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><?=$oTbl->label?></h3>
            </div>

            <div class="card-body">
                <ul class="list-group" style="display: inline-block; width:100%;">
                    <?php foreach($aFields as $oField) {
                        //var_dump($oField);
                        $bHasPerm = false;

                        if(array_key_exists($oTbl->table_name,$aUserColumns)) {
                            if(array_key_exists($oField->fieldkey,$aUserColumns[$oTbl->table_name])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <li class="list-group-item col-md-6" style="position: relative; float:left;">
                            <input type="checkbox"<?=($bHasPerm) ? ' checked' : ''?> name="<?=$this->sFormName?>-indexcolumns[]" value="<?=$oField->Field_ID?>-<?=$oTbl->table_name?>" />
                            <?=$oField->label?>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>
<?php
}

