<?php
# Get Partial Data
$aTabsByForm = $this->aPartialData['aTabs'];
$aUserTabs = $this->aPartialData['aUserTabs'];

# Print List with all Modules and Tabs
foreach(array_keys($aTabsByForm) as $sTable) {
    $oForm = $aTabsByForm[$sTable]['oForm'];
    $aTabs = $aTabsByForm[$sTable]['aTabs']; ?>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><?=$oForm->label?></h3>
            </div>

            <div class="card-body">
                <ul class="list-group" style="display: inline-block; width:100%;">
                    <?php foreach($aTabs as $oTab) {
                        //var_dump($oField);
                        $bHasPerm = false;

                        if(array_key_exists($oForm->form_key,$aUserTabs)) {
                            if(array_key_exists($oTab->Tab_ID,$aUserTabs[$oForm->form_key])) {
                                $bHasPerm = true;
                            }
                        }
                        ?>
                        <li class="list-group-item col-md-6" style="position: relative; float:left;">
                            <input type="checkbox"<?=($bHasPerm) ? ' checked' : ''?> name="<?=$this->sFormName?>-tabs[]" value="<?=$oTab->Tab_ID?>_<?=$oForm->form_key?>" />
                            <?=$oTab->title?>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>
    <?php
}

