<?php

use Application\Controller\CoreController;
use Application\Module;

# Set App Title from Database if found
$sPlcTitle = 'onePlace';
if(isset(CoreController::$aGlobalSettings['app-title'])) {
    $sPlcTitle = str_replace(['##VERSION##'], [Module::VERSION], CoreController::$aGlobalSettings['app-title']);
}
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($sPlcTitle)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('/css/style.css'))
            ->prependStylesheet($this->basePath('/vendor/@fortawesome/fontawesome-free/css/all.min.css'))
            ->prependStylesheet($this->basePath('/vendor/summernote/dist/summernote-bs4.min.css'))
            ->prependStylesheet($this->basePath('/vendor/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.min.css'))
            ->prependStylesheet($this->basePath('/vendor/filepond/dist/filepond.min.css'))
            ->prependStylesheet($this->basePath('/vendor/uppy/dist/uppy.min.css'))
            ->prependStylesheet($this->basePath('/vendor/apexcharts/dist/apexcharts.min.css'))
            ->prependStylesheet($this->basePath('/vendor/select2/dist/css/select2.min.css'))
            ->prependStylesheet($this->basePath('/vendor/bootstrap/dist/css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('/js/plc-message.js'))
            ->prependFile($this->basePath('/js/listener.js'))
            ->prependFile($this->basePath('/vendor/@fortawesome/fontawesome-free/js/all.min.js'))
            ->prependFile($this->basePath('/vendor/sweetalert/dist/sweetalert.min.js'))
            ->prependFile($this->basePath('/vendor/summernote/dist/summernote-bs4.min.js'))
            ->prependFile($this->basePath('/vendor/apexcharts/dist/apexcharts.min.js'))
            ->prependFile($this->basePath('/vendor/jquery-ui-sortable/jquery-ui.min.js'))
            ->prependFile($this->basePath('/vendor/select2/dist/js/select2.full.min.js'))
            ->prependFile($this->basePath('/vendor/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('/vendor/jquery/dist/jquery.min.js'))
        ?>

    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('/img/logo_small_inv.png') ?>" height="28" alt="oneplace"/>&nbsp;onePlace
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <?php
                        if(is_object(CoreController::$oSession->oUser)) {
                            try {
                                echo $this->partial('partial/nav-' . CoreController::$oSession->oUser->getTheme());
                            } catch (\RuntimeException $e) {
                                try {
                                    // no nav partial for theme found - load default
                                    echo $this->partial('partial/nav');
                                } catch (\RuntimeException $e) {
                                    // no nav partial found
                                }
                            }
                        } else {
                            // no nav partial for theme found - load default
                            echo $this->partial('partial/nav');
                        }
                        ?>
                    </ul>
                </div>
                <div class="text-white px-2">
                    <?php
                    if(is_object(CoreController::$oSession->oUser)) {
                        $aUserXPInfo = CoreController::$oSession->oUser->getExperience();
                    ?>
                    <?=CoreController::$oSession->oUser->getLabel()?>
                    - <small><?=$this->translate('Level')?> <?=$aUserXPInfo['level']?></small>
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: <?=$aUserXPInfo['percent']?>%" aria-valuenow="<?=$aUserXPInfo['percent']?>" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <?php } ?>
                </div>
                <span class="navbar-text px-2">
                    <a href="<?=$this->url('logout')?>" title="<?=$this->translate('Logout')?>">
                        <i class="fas fa-sign-out-alt text-white"></i>
                    </a>
                </span>
            </div>
        </nav>
        <div class="container">
            <?php
            /**
             * Print Flashmessenger messages (alerts)
             */
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat('<div%s style="">
                                 <ul><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');
            echo $flash->render('error',   ['alert', 'alert-dismissible', 'alert-danger', 'alert-plc']);
            echo $flash->render('info',    ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
            echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
            echo $flash->render('warning', ['alert', 'alert-dismissible', 'alert-warning', 'alert-plc']);
            echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success', 'alert-plc']);?>

            <?= $this->partial('partial/breadcrumb', ['aButtons'=>isset($this->aButtons) ? $this->aButtons : [], 'pages'=>[]]); ?>
            <div class="row py-4">
                <div class="col-md-12 py-4">
                    <?= $this->content ?>
                </div>
            </div>
            <hr>
            <footer>
                <p>&copy; 2010-<?= date('Y') ?> by Verein onePlace. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
