<?php

use Application\Controller\CoreController;
use OnePlace\Article\Model\ArticleTable;

$oArtTbl = CoreController::$oServiceManager->get(ArticleTable::class);

$oRecentArts = $oArtTbl->fetchAll(true, ['show_on_web_idfs' => 2]);

if(count($oRecentArts) > 0) {
?>
<!-- Men's Collection -->
<section class="men-collection gray-bg">
    <div class="container">
        <header class="text-center">
            <h2 class="text-uppercase"><small>Autumn Choice</small>Article Slider</h2>
        </header>
        <!-- Products Slider-->
        <div class="owl-carousel owl-theme products-slider">
            <?php
            foreach($oRecentArts as $oArt) {
            ?>
            <!-- item-->
            <div class="item">
                <div class="product is-gray">
                    <div class="image d-flex align-items-center justify-content-center"><img src="/data/article/<?=$oArt->getID()?>/<?=$oArt->featured_image?>" alt="product" class="img-fluid">
                        <div class="hover-overlay d-flex align-items-center justify-content-center">
                            <div class="CTA d-flex align-items-center justify-content-center"><a href="#" class="add-to-cart"><i class="fa fa-shopping-cart"></i></a><a href="/article/show/some-seo-random-name/<?=$oArt->getID()?>" class="visit-product active"><i class="icon-search"></i>View</a><a href="#" data-toggle="modal" data-target="#exampleModal" class="quick-view"><i class="fa fa-arrows-alt"></i></a></div>
                        </div>
                    </div>
                    <div class="title"><a href="/article/show/some-seo-random-name/<?=$oArt->getID()?>">
                            <h3 class="h6 text-uppercase no-margin-bottom"><?=$oArt->getLabel()?></h3></a><span class="price text-muted">$40.00</span></div>
                </div>
            </div>
            <?php } ?>
        </div>
    </div>
</section>
<?php } ?>