<!-- Brands Section-->
<section class="brands">
    <div class="container">
        <!-- Brands Slider-->
        <div class="owl-carousel owl-theme brands-slider">
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-1.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-2.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-3.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-4.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-5.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-6.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-1.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-2.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-3.svg" alt="..." class="img-fluid"></div>
            </div>
            <!-- item-->
            <div class="item d-flex align-items-center justify-content-center">
                <div class="brand d-flex align-items-center"><img src="https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/brand-4.svg" alt="..." class="img-fluid"></div>
            </div>
        </div>
    </div>
</section>