<!-- Categories Section-->
<section class="categories">
    <div class="container">
        <header class="text-center">
            <h2 class="text-uppercase"><small>Top for this month</small>Our Featured Picks</h2>
        </header>
        <div class="row text-left">
            <div class="col-lg-4"><a href="#">
                    <div style="background-image: url(https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/banner-1.jpg);" class="item d-flex align-items-end">
                        <div class="content">
                            <h3 class="h5">Men's</h3><span>New Collection</span>
                        </div>
                    </div></a></div>
            <div class="col-lg-4"><a href="#">
                    <div style="background-image: url(https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/banner-2.jpg);" class="item d-flex align-items-end">
                        <div class="content">
                            <h3 class="h5">Women's</h3><span>New Collection</span>
                        </div>
                    </div></a></div>
            <div class="col-lg-4"><a href="#">
                    <div style="background-image: url(https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/banner-3.jpg);" class="item d-flex align-items-end">
                        <div class="content">
                            <h3 class="h5">Accessories</h3><span>Sale of 20%</span>
                        </div>
                    </div></a></div>
        </div>
    </div>
</section>