<!-- Divider Section-->
<section style="background: url(https://d19m59y37dris4.cloudfront.net/hub/1-4-3/img/divider-bg.jpg);" class="divider">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <p>Old Collection                  </p>
                <h2 class="h1 text-uppercase no-margin">Huge Sales</h2>
                <p>At our outlet stores</p><a href="#" class="btn btn-template wide shop-now">Shop Now<i class="icon-bag"></i></a>
            </div>
        </div>
    </div>
</section>