<div class="col-md-4">
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Discover Modules</h2>
        </div>
        <div class="card-body">
            <p>
                onePlace is a modular application framework.
                You can find multiple compatible modules on packagist.
            </p>

            <p><a class="btn btn-success pull-right" href="https://packagist.org/?tags=oneplace" target="_blank">Explore onePlace Modules &raquo;</a></p>
        </div>
    </div>
</div>