<div class="col-md-4">
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Help &amp; Support</h2>
        </div>
        <div class="card-body">
            <p>
                If you need any help or support while working or developing with oneplace,
                you may reach us via <a href="https://1plc.ch/contact" target="_blank">e-mail</a>
                We'd love to hear any questions or feedback you may have
                regarding any release.
            </p>

            <p><a class="btn btn-success pull-right" href="https://t.me/OnePlc" target="_blank">Telegram Group &raquo;</a></p>
        </div>
    </div>
</div>