<div class="col-md-4">
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Manage Themes</h2>
        </div>
        <div class="card-body">
            <p>
                Customize the look of your app!
                We have some of the most popular premium admin templates,
                ready to integrate for you. Or just clone our default-theme
                on github.com and <a href="https://github.com/OnePlc/oneplace-theme-boilerplate" target="_blank">create your own.</a>
            </p>

            <p><a class="btn btn-success pull-right" href="/application/themes">Manage Themes &raquo;</a></p>
        </div>
    </div>
</div>