<div class="jumbotron">
    <h1>Welcome <?=$oUser->getLabel()?> to <span class="zf-green">onePlace Core</span></h1>
    <p>
        Congratulations! You have successfully installed
        <a href="https://github.com/oneplc/plc_x_core" target="_blank">onePlace Core</a>.
        This Application can serve as a simple starting point for you to begin
        building your application on onePlace Framework.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/oneplc/plc_x_core" target="_blank">Check onePlace on GitHub &raquo;</a></p>
</div>