<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Upload new theme</h2>

            <form action="" method="POST" enctype="multipart/form-data">
                <div class="form-row">
                    <label>Theme .zip File</label>
                    <input type="file" name="zip_file" class="Form-control" />
                </div>
                <div class="form-row">
                    <!-- Submit -->
                    <button type="submit" class="btn btn-primary">Install Theme</button>
                </div>
            </form>
        </div>
    </div>
</div>