<?php

use Application\Controller\CoreController;

$aVendors = json_decode(CoreController::$aGlobalSettings['app-vendors']);
$aAlreadyInstalled = [];
?>
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">
                    <?=$this->translate('Installed Modules')?>
                </h2>
            </div>
            <div class="card-body">
                <ul class="list-group">
                <?php
                foreach($aModulesInstalled as $oMod) {
                    $sPath = 'vendor/'.$oMod->vendor.'/'.$oMod->module_key.'/src/Module.php';
                    if($oMod->module_key == 'oneplace-core') {
                        $sPath = 'module/Application/src/Module.php';
                    }
                    if(file_exists($sPath)) {
                        $aModuleName = explode('-',$oMod->module_key);
                        array_shift($aModuleName);
                        $sModNamePath = $oMod->vendor;
                        foreach ($aModuleName as $sModPath) {
                            $sModNamePath .= "\\".$sModPath;
                        }
                        $aAlreadyInstalled[$oMod->module_key] = true;
                        $sClass = "$sModNamePath\\Module";
                        $sInstalledVer = '(unknown)';
                        if($oMod->module_key == 'oneplace-core') {
                            $sClass = "Application\\Module";
                        }
                        $sInstalledVer = $sClass::VERSION;

                        $sUrl = '';
                        try {
                            $sModRoute = substr($oMod->module_key,strlen($aVendors[0].'-'));
                            $sUrl = $this->url($sModRoute.'-update');
                        } catch(\RuntimeException $e) {

                        }
                        ?>
                        <li class="list-group-item">
                            <?=$oMod->label?> - <?=$oMod->version?> - <?=$sClass::VERSION?>
                            <?php if ($sUrl != '' && ($sClass::VERSION != $oMod->version)) { ?>
                                - <a href="<?=$sUrl?>" title="Update Module">
                                    Update
                                </a>
                            <?php } ?>
                        </li>
                        <?php
                    }
                    ?>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">
                    <?=$this->translate('New Modules to install')?>
                </h2>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <?php
                    foreach ($aVendors as $sVendor) {
                        $aModules = glob('vendor/'.strtolower($sVendor).'/*', GLOB_ONLYDIR);
                        foreach ($aModules as $sMod) {
                            $sModName = basename($sMod);
                            $sPackageName = 'oneplace-'.strtolower(substr($sModName,strlen('PLC_X_')));
                            if (! array_key_exists($sModName,$aModulesInstalled) && !array_key_exists($sPackageName,$aAlreadyInstalled)) {
                                $sPath = 'vendor/'.strtolower($sVendor).'/'.$sModName.'/src/Module.php';
                                //echo $sPath ."</br>";
                                if (file_exists($sPath)) {
                                    require_once $sPath;
                                    $aModuleName = explode('-',$sModName);
                                    array_shift($aModuleName);
                                    $sModNamePath = '';
                                    foreach ($aModuleName as $sModPath) {
                                        $sModNamePath .= "\\".ucfirst($sModPath);
                                    }
                                    $sClass = $sVendor.$sModNamePath."\\Module";
                                    $sClass = str_replace(['Oneplace'],['OnePlace'],$sClass);

                                    try {
                                        $sModVer = $sClass::VERSION;
                                    } catch(\RuntimeException $e) {

                                    }

                                    $sUrl = '';
                                    try {

                                        $sModRoute = substr($sModName,strlen($aVendors[0].'-'));
                                        $sUrl = $this->url($sModRoute.'-setup');
                                    } catch(\RuntimeException $e) {

                                    }

                                    if ($sUrl != '') {
                                    ?>
                                    <li class="list-group-item">
                                        <?=$sModName?> - <?=$sModVer?>
                                            - <a href="<?=$sUrl?>" title="Run Setup">
                                                Run setup
                                            </a>
                                    </li>
                                    <?php
                                    }
                                }
                            }
                        }
                    }
                    ?>
                </ul>
            </div>
        </div>
    </div>

</div>