<?php

use Application\Controller\CoreController;

?>
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">
                    <?=$this->translate('Installed Modules')?>
                </h2>
            </div>
            <div class="card-body">
                <ul class="list-group">
                <?php
                foreach($aModulesInstalled as $oMod) {
                    $sPath = 'vendor/'.$oMod->vendor.'/'.$oMod->module_key.'/src/Module.php';
                    if($oMod->module_key == 'oneplace-core') {
                        $sPath = 'module/Application/src/Module.php';
                    }
                    if(file_exists($sPath)) {
                        $sModule = str_replace(['-'],['\\'],$oMod->module_key);
                        $sClass = "$sModule\\Module";
                        $sInstalledVer = '(unknown)';
                        if($oMod->module_key == 'oneplace-core') {
                            $sClass = "Application\\Module";
                        }
                        $sInstalledVer = $sClass::VERSION;
                        ?>
                        <li class="list-group-item">
                            <?=$oMod->label?> - <?=$oMod->version?> - <?=$sClass::VERSION?>
                        </li>
                        <?php
                    }
                    ?>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">
                    <?=$this->translate('New Modules to install')?>
                </h2>
            </div>
            <div class="card-body">
                <ul class="list-group">
                    <?php
                    $aVendors = json_decode(CoreController::$aGlobalSettings['app-vendors']);
                    foreach ($aVendors as $sVendor) {
                        $aModules = glob('vendor/'.$sVendor.'/*', GLOB_ONLYDIR);
                        foreach ($aModules as $sMod) {
                            $sModName = basename($sMod);
                            if (! array_key_exists($sModName,$aModulesInstalled)) {
                                $sPath = 'vendor/'.$sVendor.'/'.$sModName.'/src/Module.php';
                                if (file_exists($sPath)) {
                                    require_once $sPath;
                                    $sClass = ucfirst($sVendor)."\\".ucfirst(explode('-',$sModName)[1])."\\Module";
                                    $sModVer = $sClass::VERSION;

                                    $sUrl = '';
                                    try {
                                        $sModRoute = substr($sModName,strlen($sVendor.'-'));
                                        echo 'try:'.$sModRoute.'-setup';
                                        $sUrl = $this->url($sModRoute.'-setup');
                                    } catch(\RuntimeException $e) {

                                    }
                                    ?>
                                    <li class="list-group-item">
                                        <?=$sModName?> - <?=$sModVer?>
                                        <?php if ($sUrl != '') { ?>
                                            - <a href="<?=$sUrl?>" title="Run Setup">
                                                Run setup
                                            </a>
                                        <?php } ?>
                                    </li>
                                    <?php
                                }
                            }
                        }
                    }
                    ?>
                </ul>
            </div>
        </div>
    </div>

</div>