<div class="jumbotron">
    <h1>Welcome <?=$oUser->getLabel()?> to <span class="zf-green">onePlace Core</span></h1>
    <p>
        Congratulations! You have successfully installed
        <a href="https://github.com/oneplc/plc_x_core" target="_blank">onePlace Core</a>.
        This Application can serve as a simple starting point for you to begin
        building your application on onePlace Framework.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/oneplc/plc_x_core" target="_blank">Check onePlace on GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Manage Themes</h2>
            </div>
            <div class="card-body">
                <p>
                    Customize the look of your app!
                    We have some of the most popular premium admin templates,
                    ready to integrate for you. Or just clone our default-theme
                    on github.com and <a href="https://github.com/OnePlc/oneplace-theme-boilerplate" target="_blank">create your own.</a>
                </p>

                <p><a class="btn btn-success pull-right" href="/application/themes">Manage Themes &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Discover Modules</h2>
            </div>
            <div class="card-body">
                <p>
                    onePlace is a modular application framework.
                    You can find multiple compatible modules on packagist.
                </p>

                <p><a class="btn btn-success pull-right" href="https://packagist.org/?tags=oneplace" target="_blank">Explore onePlace Modules &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Help &amp; Support</h2>
            </div>
            <div class="card-body">
                <p>
                    If you need any help or support while working or developing with oneplace,
                    you may reach us via <a href="https://1plc.ch/contact">e-mail</a>
                    We'd love to hear any questions or feedback you may have
                    regarding any release.
                </p>

                <p><a class="btn btn-success pull-right" href="https://1plc.ch/contact" target="_blank">Ping us on email &raquo;</a>
                 | <a class="btn btn-success pull-right" href="https://t.me/OnePlc" target="_blank">Telegram Group &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
