<?php

use Application\Controller\CoreController; ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Installed Themes</h2>

            <ul class="list-group">
                <li class="list-group-item">
                    Default
                    <?=(CoreController::$oSession->oUser->getTheme() != 'default') ? '<a href="/user/settheme/default">Activate</a>' : ''?>
                </li>
                <?php foreach(glob($_SERVER['DOCUMENT_ROOT'].'/themes/*',GLOB_ONLYDIR) as $sThemeLocation) {
                    $sTheme = basename($sThemeLocation); ?>
                    <li class="list-group-item">
                        <?=ucfirst($sTheme)?>
                        <?=(CoreController::$oSession->oUser->getTheme() != $sTheme) ? '<a href="/user/settheme/'.$sTheme.'">Activate</a>' : ''?>
                    </li>
                <?php } ?>
            </ul>

            <a href="/themes/add" class="btn btn-primary">Upload new Theme</a>
        </div>
    </div>
</div>