<?php

?>
<h1>Update</h1>
Modules that need db installation:
<ul class="list-group">
<?php
if(count($aInfo['install']) > 0) {
    foreach($aInfo['install'] as $sModule) { ?>
        <li class="list-group-item"><?=$sModule?></li>
    <?php
    }
}
?>
</ul>
<hr/>
Modules that need db upgrade:
<ul class="list-group">
    <?php
    if(count($aInfo['update']) > 0) {
        foreach($aInfo['update'] as $sModule) { ?>
            <li class="list-group-item"><?=$sModule?></li>
            <?php
        }
    }
    ?>
</ul>

<form method="POST" action="">
    <div class="form-row">
        <!-- Submit -->
        <button type="submit" class="btn btn-primary">Update</button>
    </div>
</form>