<?php if(count($aWarnings) > 0) {
    foreach($aWarnings as $sWarn) { ?>
        <div class="alert alert-warning">
            <?=$sWarn?>
        </div>
        <?php
    }
} ?>
<h1>Update</h1>
Modules that need db installation:
<ul class="list-group">
<?php
if(count($aInfo['install']) > 0) {
    foreach($aInfo['install'] as $sModule) { ?>
        <li class="list-group-item"><?=$sModule?></li>
    <?php
    }
}
?>
</ul>
<hr/>
Modules that need db upgrade:
<ul class="list-group">
    <?php
    if(count($aInfo['update']) > 0) {
        foreach($aInfo['update'] as $sModule) { ?>
            <li class="list-group-item"><?=$sModule?></li>
            <?php
        }
    }
    ?>
</ul>

<form method="POST" action="">
    <div class="form-row">
        <?php if (count($aWarnings) > 0) { ?>
            <!-- Submit -->
            <button type="submit" class="btn btn-primary" readonly="readonly" disabled>Correct warnings first</button>
        <?php } else { ?>
        <!-- Submit -->
        <button type="submit" class="btn btn-primary">Update</button>
        <?php } ?>
    </div>
</form>